### ISSUE TITLE
Is the SDK opensource?

### ISSUE THREAD

**Issue by spazziale** [gnaudio/jabra-linux-samples#2]
If yes, where can I find it?

**Comment by pehandersen-jabra** [comment]
The SDK itself is not opensource no - you can find it here: https://developer.jabra.com/site/global/sdk/linux/index.gsp
License agreement can be found here: https://developer.jabra.com/site/global/legal/license-agreement.gsp

If you do have additional questions on the SDK itself, we'd encourage you to sign up on the developer portal above and submit a ticket.

**Comment by Ho-Ro** [comment]
One remark, both links above -> 404 :(
According to Jabra, the Linux SDK is [no longer available](https://developer.jabra.com/sdks-and-tools/linux):
> No c++ SDK available for download
We only offer a Linux SDK for c++ development by request.

Your example is a good starting point, after changing `"Jabra Link 380"` to `"Jabra Link 370"` it detects my Jabra75 dongle and headset.
I put the lib into `/usr/local/lib` and use a simple Makefile instead of VS code:
```Makefile
JabraBTlinkqualityBattery: JabraBTlinkqualityBattery.cpp
	g++ $< -o $@ -ljabra
```

**Comment by pehandersen-jabra** [comment]
Updated link: https://developer.jabra.com/sdks-and-tools/linux
Indeed as you mention, this is only available by request now. Please go to https://developer.jabra.com/support/ and send a request, if you need it.
